build:
  stage: build
  image: rbonifaz/wahay-rpm-build:latest
  before_script:
    - dnf install -y xorg-x11-server-Xvfb
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$FEDORA_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
    - 'echo -e "[fedora.autonomia.digital]:4242,[185.108.78.22]:4242 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIx8qF3puSAM1UAxc3ODJTNGrgwf8mET664pPfP/ZQgiMxTIKG8Ar8h1xxP52AyQoqTLpCWOPaBkUya2Q0+SZTg=
" > ~/.ssh/known_hosts'
    - chmod 644 ~/.ssh/known_hosts

  script:
    - git clone https://github.com/gotk3/gotk3.git
    - cd gotk3/
    - git checkout tags/v0.4.0
    - cd ..
    - mv gotk3 gotk3-0.4.0/
    - tar zcf gotk3-0.4.0.tar.gz gotk3-0.4.0/
    - mkdir f30 f31
    - fedpkg --release f30 local
    - 'find . -name "*fc30*.rpm" -exec mv {} f30 \;'
    - fedpkg --release f31 local
    - 'find . -name "*fc31*.rpm" -exec mv {} f31 \;'
    - 'scp -r -P4242 f30/* fedora-repo@fedora.autonomia.digital:packages/upload/f30'
    - 'scp -r -P4242 f31/* fedora-repo@fedora.autonomia.digital:packages/upload/f31'

  artifacts:
    paths:
      - 'f30/*.rpm'
      - 'f31/*.rpm'
