# Generated by go2rpm 1
%bcond_without check

# https://github.com/gotk3/gotk3
%global goipath         github.com/gotk3/gotk3
Version:                0.4.0

%gometa

%global common_description %{expand:
Go bindings for GTK3.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTIONS.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go bindings for GTK3

License:        ISC
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Mar 16 11:46:50 -05 2020 rafael <rafael@autonomia.digital> - 0.4.0-1
- Initial package

